version: "3.7"
volumes:
  mongodb_data_container:
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    links:
      - server
    ports:
      - "3000:3000"
    volumes:
       - ./client/src:/app/src
    environment:
      API_URL: http://localhost:3001
  server:
    build:
      context: ./server
    command: ["npm", "run", "watch"]
    ports:
      - "3001:3001"
    volumes:
       - ./server:/app/
       - /app/node_modules
    links:
      - mongodb
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

